version: "3.9"

services:
  backend:
    build:
      context: backend
    image: ${REGISTRY:-theimposter}/backend:${IMAGE_TAG:-latest}
    environment:
      - RUST_LOG=info
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: unless-stopped

  caddy:
    build:
      context: .
      dockerfile: deploy/caddy/Dockerfile
    image: ${REGISTRY:-theimposter}/frontend:${IMAGE_TAG:-latest}
    environment:
      DOMAIN: ${DOMAIN:-theimposter.test}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
